"""Narrow integration seams; implementations belong to later branches."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol


class BudgetBroker(Protocol):
    def available(self) -> float: ...
    def reserve(self, reservation_id: str, amount: float) -> bool: ...
    def release(self, reservation_id: str) -> None: ...


class MotionDetourRunner(Protocol):
    def launch(self, run_path: Path, *, scene: str, seed: int, policy: str, horizon: int) -> None: ...
    def stop(self, run_path: Path) -> bool: ...
    def connectivity_ok(self) -> bool: ...
    def technical_health(self) -> bool: ...
    def detour_metrics(self, run_path: Path) -> dict[str, float] | None: ...
