"""Narrow integration seams; implementations belong to later branches."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol


class GeminiLedger(Protocol):
    def available_micro_usd(self) -> int: ...
    def reserve_block(self, allocation_id: str, amount_micro_usd: int) -> bool: ...
    def draw(self, allocation_id: str, request_id: str, amount_micro_usd: int) -> bool: ...


class MotionDetourRunner(Protocol):
    def launch(self, run_path: Path, *, scene: str, seed: int, policy: str, horizon_m: int) -> None: ...
    def stop(self, run_path: Path) -> bool: ...
    def connectivity_ok(self) -> bool: ...
    def technical_health(self) -> bool: ...
    def detour_metrics(self, run_path: Path) -> dict[str, float] | None: ...
